### ISSUE TITLE
Downlink RX2 channel is using incorrect parameters

### ISSUE THREAD

**Issue by illperipherals** [helium/router#214]
working on this sparkfun board:
https://www.sparkfun.com/products/17506?_ga=2.63543343.1013225684.1613409402-1824805981.1610045593

For US915, the downlink channels can only use DR8 – DR13 (all 500kHz).  Furthermore, the second receive window (RX2) must only use 923.3/DR8.  It would seem that the Join Accept may have specified the RX2 Data Rate as DR0.

![image](https://user-images.githubusercontent.com/17368055/107976561-60c53a00-6f7f-11eb-83cb-94f20f48a33f.png)
![image](https://user-images.githubusercontent.com/17368055/107976574-67ec4800-6f7f-11eb-9a4f-4b59e08465ea.png)

**Comment by jdgemm** [comment]
Unable to replicate, will open again if appears.
