### ISSUE TITLE
Possible FCntUp Bug

### ISSUE THREAD

**Issue by lthiery** [helium/router#256]
Router appears to not tolerate a confirmed frame being resent. Router appears to assume that its confirmation is well received by the end-device. It is quite possible for the device to not receive the ACK, in which case the specification says:

"The FCnt is not incremented in case of multiple transmissions of an unconfirmed frame (see NbTrans parameter), **or in the case of a confirmed frame that is not acknowledged**."

![ack_bug](https://user-images.githubusercontent.com/1606640/112521514-d62fe180-8d59-11eb-8692-35d98b89de4c.png)

In this example, the `FCntUp = 28` frame is received and acknowledged by Router, but the Device did not receive it. The Device tries to send the frame up again, but it appears that Router makes the frame as "late" instead of a retry on behalf of the device.

**Comment by macpie** [comment]
Should be fixed in https://github.com/helium/router/pull/253

**Comment by macpie** [comment]
Fixed
