### ISSUE TITLE
CN470 tx power too high

### ISSUE THREAD

**Issue by lthiery** [helium/router#257]
Transmit no higher than 17

![image](https://user-images.githubusercontent.com/1606640/112871152-d0950d00-9073-11eb-8f41-013a0e2b7ad0.png)

Is this handled for Europe? @macpie

**Comment by macpie** [comment]
I am guessing this depends on region?

**Comment by lthiery** [comment]
Yes, transmit power will depend on region. As does datarate for example, so I would try to keep them compartmentalized in similar ways.

**Comment by lthiery** [comment]
Found this fella this morning @macpie @michaeldjeffrey 
![image](https://user-images.githubusercontent.com/1606640/112880795-c6790b80-907f-11eb-9913-ee313c5b6727.png)

**Comment by macpie** [comment]
This had been merged
