### ISSUE TITLE
Out of order FCntUp

### ISSUE THREAD

**Issue by lthiery** [helium/router#264]
FCnt 25 is delivered VERY late by a hotspot (8 hours after the original?)

It is still purchased, even though FCntUp is otherwise at 33.

![image](https://user-images.githubusercontent.com/1606640/113204997-9ae25680-9222-11eb-8191-3f05524f3727.png)

**Comment by macpie** [comment]
I think, this is due to:

1. A router restart which reset the fcnt (I have a fix for this)
2. An obvious very late delivery of some old packets

**Comment by macpie** [comment]
Fix here https://github.com/helium/router/pull/275

**Comment by jdgemm** [comment]
Fixed
