### ISSUE TITLE
Set RxDelay for devices in console

### ISSUE THREAD

**Issue by jerryyip** [helium/router#339]
As hotspots get downlink packets from the p2p network, the network latency is higher than the traditional UDP network, which will frequently cause `Packet REJECTED` in pktfwd. To avoid this situation, users may need to set RxDelay from 1 to 5 on their devices.

**Comment by jdgemm** [comment]
This has been addressed with recent updates. If you are still seeing please raise an additional ticket.

**Comment by buzzware** [comment]
How was this addressed? I don't see an RxDelay option in console, and we are seeing downlink issues again (#519, #517), which this would help resolve/avoid. I think this should be re-opened. @jdgemm

**Comment by jdgemm** [comment]
new issue https://github.com/helium/router/issues/531 filed here @buzzware
