### ISSUE TITLE
Joining issue on the network - use 27dBm on RX2 windows in EU868

### ISSUE THREAD

**Issue by disk91** [helium/router#364]
Currently we are experiencing a lot of difficulties to join the network, different issues has been identify and impact the router logic:
- It's not clear what power is used for RX2 windows (as the RX1 power was wrong previously)  Make sure we have 27dBm power for EU868 as low power join accept creates a budget link issue for indoor devices or noisy environnement.

**Comment by michaeldjeffrey** [comment]
Sorry, forgot to link this issue in the PR. 
EU868 downlink strength was raised to 27dBm for applicable frequency ranges in https://github.com/helium/router/pull/355
