### ISSUE TITLE
GRPC server not restarting

### ISSUE THREAD

**Issue by macpie** [helium/router#370]
It seems like the GRPC server can crash and not get restarted.

**Comment by lthiery** [comment]
Are there logs? @macpie

**Comment by macpie** [comment]
Not that I could find so far

**Comment by jdgemm** [comment]
@andymck I believe you pushed out a fix for this, please confirm and we can close, thanks...

**Comment by andymck** [comment]
@jdgemm A fix has been deployed and confirmed as working.  closing.....
