### ISSUE TITLE
Join failures and bursts of packets

### ISSUE THREAD

**Issue by pooley92** [helium/router#385]
I've been having issues joining today 23rd July. 

At midnight 12:00am bst I noticed a burst of data packets coming through. As well as my old joins. This is using staging console.

Device examples

Dev eui
A840417D11829434

1D4A7D0000A49A12

![image](https://user-images.githubusercontent.com/75324434/126850044-dd9034b8-da4d-4f35-acc3-1c6365784071.jpeg)![image](https://user-images.githubusercontent.com/75324434/126850050-92f9384c-dfe4-4c56-aed1-809b015c0f7e.jpeg)

**Comment by jdgemm** [comment]
Closing this as we believe will be addressed with later miner release here: https://engineering.helium.com/2021/08/06/blockchain-release-snapshot-update.html
