### ISSUE TITLE
Multi packet issues

### ISSUE THREAD

**Issue by BFGNeil** [helium/router#396]
Running the Wio Terminal mapper and I have all packets turned on.

Lots are returning late, even tho its by MS, and often means I get a lost response (even tho one went through)

example here:

<img width="1028" alt="Screenshot 2021-08-09 at 15 25 35" src="https://user-images.githubusercontent.com/79230094/128835991-b9a37ffc-eb93-43d7-8d67-2b767e0b8fcf.png">

**Comment by jdgemm** [comment]
We're investigating.

**Comment by macpie** [comment]
@BFGNeil Could you find out what was the hold time for the initial and late packet? The `hold_time` is a value given to the integrations, you can also use the debug mode to find it.

**Comment by BFGNeil** [comment]
All I can see is: 

{
  "id": "3504a146-a708-4686-94e8-847c6f976060",
  "router_uuid": "1c466a1b-2cd3-4ac1-a23a-ebfce68f672f",
  "category": "uplink_dropped",
  "sub_category": "uplink_dropped_late",
  "description": "Late packet",
  "reported_at": "1628931730065"
}

am I missing something? debug on console doesn't seem to have hold_time

**Comment by BFGNeil** [comment]
"hold_time": 475, late packet does not list a hold_time

**Comment by macpie** [comment]
Looks like the hotspot held on to the packet a little longer than the the threshold (400ms currently). A few fixes were implemented to improve hold time but it does not seems to always be enough.

I believe we should rethink how we timeout for packets and maybe allow longer if we do not intend to send a downlink to the device. We then will be able to capture more packets and avoid the infamous "late packet issue".

This will be my top priority.

**Comment by macpie** [comment]
This should be improved with #410. 

Following our release schedule we will tag today for a week of testing and release next week.

**Comment by macpie** [comment]
This is not fully fixed just yet

**Comment by macpie** [comment]
Moving here https://github.com/helium/router/issues/412
