### ISSUE TITLE
docker exec helium_router router dc_tracker info all always results in "no matches"

### ISSUE THREAD

**Issue by mfalkvidd** [helium/router#400]
1. Are you using Helium hosted Console or running your own open source Console?

My own. Built from d2b6af6bb85acda507cc4cfbcc83a8d2dc786418

Please describe your issue:
`docker exec helium_router router dc_tracker info all` always returns
```
no matches
ok
```

I have created 4 organizations and added a few devices so I think I should see some output.

**Comment by macpie** [comment]
`router dc_tracker info all` will only return if DC were charged to an organization. 

Also as this is using a in memory cache, every router restart will clear the cache (the "real" values are held into console's DB).
