### ISSUE TITLE
Packets from someone else

### ISSUE THREAD

**Issue by AkosLukacs** [helium/router#417]
1. Are you using Helium hosted Console or running your own open source Console?
Official production console

2. If you are on Helium hosted Console, which url are you currently on? 
https://console.helium.com

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
Org name: "Bippp"
Device id: c62b05f8-a78d-4905-9320-13550eb424a3

Please describe your issue:

Saw packets from someone else. I know sounds strange, but the Event Log shows lots of packets received by hotspots in Sweden  (today) and Romania (yesterday).
No, I did not commit the code with the EUI and key in it. And packets are received is from two distinct places, so it's not even one "device" I saw packets from.
And my actual device was offline in the last couple of days.

For example:
| hotspot | Time |
|----------|-------|
| [loud-crepe-dalmatian (Sweden) ](https://explorer.helium.com/hotspots/11ENRzYQQhhHZ4SayScKpejCKzmEsePXdr8GtH1bMQfZwbQvEWo) |  Aug 27, 2021 10:11:35.845 AM |
| [rural-blonde-unicorn (Sweden) ](https://explorer.helium.com/hotspots/112KmHQcppMQhuoxeX7jSJ7pMqqXACkuarYkBdePL9J8C3kGwgQh) | Aug 27, 2021 10:10:03.292 AM |
| [large-tawny-gorilla (Romania)](https://explorer.helium.com/hotspots/112HfvvUEhoiA8GccDuCxRVBiFCTD3Hi1oiqzDxKNggKRMYVpEB) | Aug 26, 2021 10:51:25.454 PM |
| [delightful-metal-nuthatch (Romania)](https://explorer.helium.com/hotspots/11Bp5eWvLW2rr4g4dEco5bytpByX7Ve6h4S8KZfoc7ptQaZFw73) |  Aug 26, 2021 10:51:25.449 PM |

Might be interesting, but not necessarily that my DC balance is 0 right now, so all packets reported as dropped.
But someone else with enough DC [mentioned the same issue in Discord #console](https://discord.com/channels/404106811252408320/730245319882965093/880772698874208287)

From the debug json: 
```json
  {
    "category": "uplink_dropped",
    "data": {
      "fcnt": 1,
      "hotspot": {
        "id": "11ENRzYQQhhHZ4SayScKpejCKzmEsePXdr8GtH1bMQfZwbQvEWo",
        "name": "loud-crepe-dalmatian"
      }
    },
    "description": "Not enough DC",
    "device_id": "c62b05f8-a78d-4905-9320-13550eb424a3",
    "frame_down": null,
    "frame_up": 1,
    "id": "6572bf13-9fed-465d-bfd7-10b4d5fa2a24",
    "organization_id": "ac6e5864-7ec7-4cf6-bd29-7710180efa3c",
    "reported_at": "1630051895845",
    "router_uuid": "486455db-fdd4-4e3b-ac86-cceb913b8a89",
    "sub_category": "uplink_dropped_not_enough_dc"
  }
```

**Comment by AkosLukacs** [comment]
Quick update: 
New packets at the same device's Log around Aug 28, 2021 12:39:59.958 PM. From Germany this time
And a different device of mine (96d97076-7366-4894-a7e0-bae1d0b19aad) picked up packets at around Aug 28, 2021 9:51:26.949 AM. These are from Hungary...

**Comment by macpie** [comment]
This is most likely due to `devaddr` collision. We have made some improvement to this recently but `uplink_dropped_not_enough_dc` seemed to have been forgotten.

**Comment by michaeldjeffrey** [comment]
We had quite a few stale devices sitting in Router that were causing this issue to occur. They've been pruned. 
Open a new issue if this continues. Thank you
