### ISSUE TITLE
Reduce transmit power for different RSSI/SNR

### ISSUE THREAD

**Issue by lthiery** [helium/router#426]
This is a bit of a placeholder ticket, but often people are testing devices very close to a gateway. If RSSI is at -30 for example, the gateway does not need to transmit at max power and it can, in fact, be detrimental as the transmit is "too loud". 

We could go so far as having a whole table of ranges and typical transmit power while also taking antenna gain into account.

**Comment by mikev** [comment]
Potential cause or associated issue.  Miner is reporting too high rssi values.
 https://github.com/helium/miner/pull/1317
