### ISSUE TITLE
Documentation Effort

### ISSUE THREAD

**Issue by macpie** [helium/router#427]
- [x] Docs need their own directory
- [x] CLI
- [x] Env variables
- [x] Metrics
- [x] Lora support
- [x] Runbooks -- e.g, what to do at 2 AM when Pager Duty alerts and you're half asleep

**Comment by buzzware** [comment]
https://github.com/helium/router/issues/507

**Comment by dpezely** [comment]
Adding to this list:
- [ ] Runbooks -- e.g, what to do at 2 AM when Pager Duty alerts and you're half asleep

In the short term, I'll add instructions based upon extraction of shell history from various production servers with any sensitive information elided, of course.  Most of this *could* go within each repo's `docs` subdirectory: router, packet-purchaser, etc. but open to suggestions.

Examples:
- start/stop runtime via `docker` or `docker-compose`, etc.
- create a snapshot
- load from a snapshot
- interrogate health of the system via *some* of the aliases; e.g., `pp sc list` for summary of State Channels
- etc.

**Comment by dpezely** [comment]
Draft PR for new router runbook: https://github.com/helium/router/pull/667
