### ISSUE TITLE
LoRaWAN Config Request: No CFList on EU868

### ISSUE THREAD

**Issue by lthiery** [helium/router#433]
There are some LoRaWAN devices being sold for regions like Europe, where they only know how to function on 3 channels. This is technically LoRaWAN compliant and therefore we need a way for the user to disable CFList (which otherwise expands the device to use 5 additional channels).

**Comment by macpie** [comment]
Is that the option you are talking about?

![Screen Shot 2021-09-24 at 15 37 52](https://user-images.githubusercontent.com/778101/134746413-fea4490a-c026-49b1-9d71-bc5efb2881d6.png)

**Comment by macpie** [comment]
We only support disabling for US915 we would need to add support for EU868

**Comment by jdgemm** [comment]
internal ref: 10293

**Comment by jdgemm** [comment]
Thanks for raising this issue, we have come up with a plan and have put added it to our backlog.
