### ISSUE TITLE
Failed to queue downlink: device_region_unknown

### ISSUE THREAD

**Issue by CanEmreUnal** [helium/router#447]
I'm facing trouble between device and Helium LoraWAN connectivity. As you can see below, I'm getting the 'device_region_unknown' error and also join accept and uplinks not coming to device. (There is no uplink is going at all)

As I know we are using a compatible frequency range. 

I need some help on this. Thanks!

Note: Using the console.helium for debugging and there is a http integration between device to network.

```
{
  "category": "downlink_dropped",
  "data": {
    "integration": {
      "id": "console_websocket",
      "name": "******",
      "status": "error"
    }
  },
  "description": "**Failed to queue downlink: device_region_unknown**",
  "device_id": "b200b692-163d-4a82-99c9-7e0b89f52c74",
  "device_name": "1rduhnr9i6igfgyyoi9z",
  "frame_down": null,
  "frame_up": null,
  "id": "3c3aead8-0bbe-4e86-857d-a0ab20dceefc",
  "inserted_at": "2021-10-04T19:57:01",
  "organization_id": "e70c2e65-d069-425f-986f-cb11eaab9b4f",
  "reported_at": "1633377421855",
  "reported_at_epoch": 1633377421855,
  "reported_at_naive": "2021-10-04T19:57:01",
  "router_uuid": "45bcf5da-e9cb-4994-a74f-0d59076fe95d",
  "sub_category": "downlink_dropped_misc",
  "updated_at": "2021-10-04T19:57:01"
}
```

**Comment by michaeldjeffrey** [comment]
Different regions have varying restrictions on the size of downlink payloads. 
Until your device has successfully joined the network at least 1 time through a gateway with a known location the Helium LNS will not queue downlinks for that device.

If you're having trouble joining, make sure your devices identifying information is correct between Console and the Device.
