### ISSUE TITLE
Support `key.0` intemplating

### ISSUE THREAD

**Issue by noraneto** [helium/router#451]
We noticed that occasionally packets get delayed in processing about 19 minutes. What ever may have caused this delay the reported_at key value in the packet was set according to the processed time not the actual reception time by the gateway. I assume the correct behaviour would have been reported_at to be timestamped in GW according to the receiving time. Could you please check this?

**Comment by macpie** [comment]
The `hold_time` should be in your integration data, see https://github.com/helium/router#integrations-data

**Comment by macpie** [comment]
Looks like our bbmustache library does not support `key.0`

I got around doing this but warning cause it will fold over all the `hotspots`in the list and print `hold_time` multiple time.

```
{
  "id": "{{id}}",
  "name": "{{name}}",
  "app_eui": "{{app_eui}}",
  "dev_eui": "{{dev_eui}}",
  "devaddr": "{{devaddr}}",
  "downlink_url": "{{downlink_url}}",
  "fcnt": {{fcnt}},
  "port": "{{port}}",
  "payload": "{{payload}}",
  "reported_at": "{{reported_at}}",
   {{#hotspots}} "hold_time": "{{hold_time}}"{{/hotspots}}
}
```
