### ISSUE TITLE
After successfully joining the network, the end-device uplinks are not heard by the network.

### ISSUE THREAD

**Issue by illperipherals** [helium/router#465]
Observation:  Device joined network on channel in Frequency Sub-band 2, FSB2 (903.9MHz – 905.3MHz, FSB2).  Device uplink was sent on channel in FSB6 (910.3MHz – 911.7MHz).

Diagnosis: Helium gateways, within communication range of our end-device, are operating in FSB2 only.  So, any uplink sent on another FSB would not be heard by the network.  This is especially problematic in ultra-low power devices which primarily send unconfirmed messages for common data uplink and reserve confirmed messages for critical data.

LoRaWAN Compliance Requirement: The end-device is expected to cycle through all the uplink channels (64 125kHz channels and 8 500kHz channels) and try to use them.  The network may restrict that channel set by using a LinkAdrReq command.

End-Device Hack:

Restrict the default channel mask on the end-device to FSB2.
Preferred Solution: Network should make use of LinkAdrReq to restrict channel set to those gateways within the end-device’s communication range.  If the intent is for Helium to just use FSB2, then this should be quite an easy change to make.  However, to further improve network capacity, Gateways should be configured across FSB1 – FSB8 as this would reduce chances for contention and greatly increase capacity.  That would require LNS-to-Gateway Protocol to provide methods for the Gateway to report its FSB configuration or for the LNS to instruct the Gateway to use a particular FSB.  Additionally, your Proof-of-Coverage algorithm could be augmented to incentivize Gateways to operate on a particular FSB to increase your network capacity.

**Comment by jdgemm** [comment]
@illperipherals please confirm this issue was resolved with the emergency release for dropped packets (assuming Hotspot has deployed fixes): https://engineering.helium.com/2021/10/29/miner-emergency-release.html
Note: until manufacturers have deployed the fix, the issue will persist.

**Comment by buzzware** [comment]
SenseCap still have not updated, and that is my only gateway

**Comment by jdgemm** [comment]
@illperipherals please provide an update
