### ISSUE TITLE
Provide hold_time for Join Requests

### ISSUE THREAD

**Issue by jdgemm** [helium/router#468]
Currently we provide hold_time for uplinks and send this information to Console to be displayed in the debug window. Just as this is very helpful with determining why downlink windows are being missed, it would be equally helpful to know the same for joins.

**Comment by dpezely** [comment]
Hold Time gets computed via State Channel within core and comes to router via `handle_packet(SCPacket,...)` in `src/device/router_device_routing.erl`.

Specifically, it gets extracted from the State Channel packet:
```erlang
HoldTime = blockchain_state_channel_packet_v1:hold_time(SCPacket)
```
michaeldjeffrey captured this so it flows through router to `send_join_to_channel()` in `src/device/router_device_channels_worker.erl` which was merged as PR#455 (issue 387).  That much should land in production today tagged as 2021.11.03.0 release.

All that's remaining to do is add this to the `map` (hash-table) supplied to custom JavaScript decoders for integrations, and add tests.  (That `map` gets supplied as new optional third param to those JS functions, merged as PR#472 and should also be in production as of same 2021.11.03.0.)
