### ISSUE TITLE
Payload in JoinRequest is empty

### ISSUE THREAD

**Issue by Synthex-Moon** [helium/router#471]
The Payload JoinRequest is empty ... 
but must contain DevNonce, AppEUI and DevEUI

![image](https://user-images.githubusercontent.com/80596341/137803859-d6bcd58c-0914-4ea1-beae-373aa8cef938.png)

**Comment by macpie** [comment]
This is a duplicate of #464 and will be looked at in [milestone 2](https://github.com/helium/router/milestone/2)
