### ISSUE TITLE
Unable to Join.  Devices do not recognize the Join Accept messages

### ISSUE THREAD

**Issue by Max-Plastix** [helium/router#477]
Beginning on 2021-10-27, my devices that were functional on the Helium network have become unable to Join at all.

The Console shows the Join Request received, and Join Accept is sent as expected.
The device does not recognize the Join Accept message, and retries the Join Request again.
Both the Join Request and Join Accept messages appear correctly-formed and without error in Helium Console Debug.

Join Accept
Join Request
Join Accept
Join Request
... repeating every few seconds.

This behavior is identical across diverse device implementations (Victor Trap, Heltec CubeCell, Dragino devices, etc).  The nearest hotspot is a RAK MNTD Gold 2.0, but physically travelling to a different hotspot showed the same failing behavior.  The hotspots are functioning fine otherwise, fully sync'd and online, witnessing fine.

This has been persistent for about 48 hours, with thousands of Join Request/Accept pairs logged and no uplink/downlink packets sent from any device.

**Comment by Max-Plastix** [comment]
Same results on Staging Console.

**Comment by Max-Plastix** [comment]
Addressed through Miner fix here https://github.com/helium/miner/pull/1148

**Comment by slavendam** [comment]
After fix, it happens that we get repeated Uplink if Multiple packets are turned on. So repeated Uplink is from different hotspot instead it is grouped together. @jdgemm 

![image](https://user-images.githubusercontent.com/19354024/139559189-d0109075-dfe7-414e-a50f-52f5bfbdb2f5.png)

**Comment by Max-Plastix** [comment]
For this observed Miner issue, I can confirm that I saw it in RAKwireless v2021.10.27.0, and it is fully resolved here with 2021.10.29.0 now.  I'm going to close this one out.

Thanks devs for the quick analysis and turnaround!
