### ISSUE TITLE
Join Accept Not Receiving By Device

### ISSUE THREAD

**Issue by CanEmreUnal** [helium/router#491]
Facing same with [#437](https://github.com/helium/router/issues/478).

Hotspot already updated and working. [2021.10.29.0](https://engineering.helium.com/2021/10/29/miner-emergency-release.html)

Sharing the devices below.

4abb7e0a-aa67-4b28-83ce-44ed5440475b
f515a30a-96f5-41e7-82c7-52e10a617fc2

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/17678145/139951011-5af0ea37-c6f8-4f53-975e-f5e5fcedb2f5.png">

**Comment by CanEmreUnal** [comment]
Is there any help on here. Thanks

**Comment by macpie** [comment]
It seems like `f515a30a-96f5-41e7-82c7-52e10a617fc2` has been sending uplinks recently (2021-11-21 15:49:40).
I have not seen any joins or uplink for `4abb7e0a-aa67-4b28-83ce-44ed5440475b`
