### ISSUE TITLE
config/release.exs point to inet6, is that normal

### ISSUE THREAD

**Issue by disk91** [helium/router#493]
In the release.exs
```
http: [:inet6, port: 4000],
```
is that normal to have inet6 ? does it means that it is using ipv6 interface ?
I had some trouble to getting started my router and it has been fixed apparently once i make it listening on ipv6. 

If related to ipv6, what is the recommended setup to use ipv4 ?

**Comment by jdgemm** [comment]
@disk91 any additional info, if not will close this
