### ISSUE TITLE
Offer rejections multi_buy_too_many_attempts

### ISSUE THREAD

**Issue by macpie** [helium/router#501]
We are seeing an increasing number of packets getting rejected because of `multi_buy_too_many_attempts`. This should only be a corner case and need to be investigated further.

**Comment by dpezely** [comment]
As part of discovery for determining the cause of this issue:
Created a test that ruled-out false positives from the bloom filter by using data sampled from prod.  The new test expands upon an existing unit test but uses an external data file, so that we don't leak real data through git repo.
