### ISSUE TITLE
Add docs describing how to set up this router for testing and debugging

### ISSUE THREAD

**Issue by buzzware** [helium/router#507]
I have ordered a RAK WisGate Developer Base RAK7271 and would like  to test and debug this project on my own hardware.
Please provide documentation on what is required for this. 
Do I need to spend $900 on a OUI etc ? 
Do I need to also set up my own instance of console?

https://www.disk91.com/2021/technology/lora/make-your-own-private-network-on-top-of-helium-iot-network

**Comment by jdgemm** [comment]
Documentation here: https://docs.helium.com/use-the-network/run-a-network-server/
Youtube video here: https://youtu.be/TssqZYt1plA
