### ISSUE TITLE
Unable to downlink to devices due to high hold_time

### ISSUE THREAD

**Issue by nilotnas** [helium/router#519]
This is a follow up on issue #338 .

After a couple of months from confirming that the high `hold_time` issue was fixed I started testing devices again and noticed the issue was back. 

The behavior is the same as I described in issue #338: `hold_time` is above the downlink threshold (which is 2 seconds), and so it will never get picked up by the device. 

I have also noticed a correlation between how often the device transmits data and `hold_time`. When I have a device transmitting every 30 seconds or every minute the `hold_time` goes down and I can see some downlinks going through. For a device transmitting every 5 minutes the `hold_time` goes above the 2-second threshold and it will no longer get downlinks.

I have attached below `hold_time` plots from the past month and from 9 days ago. I am continuously monitoring my devices everyday and have seen no change in this behavior.

<img src="https://user-images.githubusercontent.com/30098970/143299132-27f0aa8a-cc86-4ae2-83c5-d7f1a5d8133a.png" width=50% height=50%><img src="https://user-images.githubusercontent.com/30098970/143299139-9bcd6ea8-911d-406e-b922-5ee8f785efc9.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/30098970/143299137-e6e1024c-fb48-4717-907a-dca44c6c3fcc.png" width=50% height=50%>

**Comment by buzzware** [comment]
Can anyone explain why the transmit period would have anything to do with hold_time?

**Comment by macpie** [comment]
Fixed RX delay https://github.com/helium/router/pull/548
