### ISSUE TITLE
Infinite JoinReq-JoinAcc in Console, device can't join

### ISSUE THREAD

**Issue by slavendam** [helium/router#520]
Few of our users reported they can't join network.
They see Join Request and Join Accept in Console, but device is not getting Join Accept.
It is tested with GLAMOS Walker device and RAK WisNode.
Biggest testing was done in Costa Rica where Join Requests were received by 4 different hotspots, but devices can't see none of Join Accepts.

I believe this issue can be connected with long hold time (even console says that Join Accept is sent with 2s delay) or maybe not sending JoinAcc? Same thing was like 2 months ago.

**Comment by buzzware** [comment]
Right now on a Heltec, I can't get either of 2 devices to show packets at all in the Helium console.
They have both been working in recent times.
I can see on the Heltec's own lora uplink log that the join requests are received, but nothing in the downlink log.
The network needs better status monitoring.

**Comment by macpie** [comment]
Is this still an issue and if yes would you guys mind providing device information (Console device UUID at least)?

**Comment by slavendam** [comment]
In last 10 days users were able to join network, not sure what was going on. So I will close this issue now.
