### ISSUE TITLE
HTTP channel timeout overload

### ISSUE THREAD

**Issue by michaeldjeffrey** [helium/router#521]
If you make an HTTP channel, and the endpoint never returns, it will timeout after the default 8 seconds.

If a device transmits at a faster rate than the timeout, or a hotspot makes it way back into a state channel and sends all the messages it's been holding. The channels_worker will start to accumulate messages since http_channel is a blocking request.

**Comment by macpie** [comment]
Fixed with https://github.com/helium/router/pull/550
