### ISSUE TITLE
no data transfer and otaa possible since update to 2.1.7 

### ISSUE THREAD

**Issue by fishpepper** [helium/router#532]
I am using staging-console.helium.wtf to relay data from commercial lora sensors.
Around 1h after the update my data transfers stopped. I can also no longer onboard (OTAA) new sensors on staging-console.helium.wtf.
However doing the same on console.helium.com works fine. So i think it has to do with last nights update... Is it just me or is something broken?

**Comment by fishpepper** [comment]
the fix brought it back to life. however it looks like staging is dropping packets again, for some devices I see gaps in the packet nonce and some sensors stopped completely :(

**Comment by macpie** [comment]
> The fix brought it back to life. thanks for your quick response! I really appreciate your work :) It looks like staging is dropping packets again, for some devices I see gaps in the packet nonce and some sensors stopped completely :(

Is this still going on for your device? If yes, can you provide the Console device ID as well as how often does your device transfers data?

**Comment by fishpepper** [comment]
Now its working. I just tested OTAA with a new sensor on staging. Thanks!

**Comment by macpie** [comment]
Fix by https://github.com/helium/router/pull/546
