### ISSUE TITLE
AS923-3 frequencies marked as `incorrect_frequency` after PoC_v11 upgrade.

### ISSUE THREAD

**Issue by carlrakwireless** [helium/router#549]
After the POCv11, hotspots in the Philippines (AS923-3) suddenly got ALL invalid beacons and witnesses. There was no change in the frequency when the upgrade to POCv11 happened. It was still the the same AS923-3 uplink frequencies but those are now `incorrect_frequency`. Did we missed something in the config file or something related to that?

Here's the screenshot of the frequency and the invalid witnessing caused by `incorrect_frequency`.

![image](https://user-images.githubusercontent.com/72064743/145983544-31a85f86-9b6f-48f1-b399-5c9c121b836c.png)

I hope the helium team can have a look and make the fix soon.

**Comment by shockool** [comment]
any update on this?

**Comment by jdgemm** [comment]
Thanks for raising the issue, but it's the incorrect repository. Please raise your issue here: https://github.com/gradoj/hplans/issues
