### ISSUE TITLE
CfList in US JoinAccept should not alternate

### ISSUE THREAD

**Issue by lthiery** [helium/router#556]
When a user enables CfList for a US915 device, the CfList inclusion in the JoinAccept frame alternates. This made sense before the user could enable CfList, but now that they explicitly enable this feature which is by default disabled, it does not seem sensible   anymore.

When a user enables CfList for a US915 device, it should always be included.

**Comment by mikev** [comment]
Here is the current documentation for the CF List enable feature in the device profile:

>Enable Join-Accept CF List (applicable to US915 devices only)
>The Join-Accept CF List configures channels according to the LoRaWAN spec to use sub-band 2. Devices that have not correctly implemented the LoRaWAN spec may experience transfer issues when this setting is enabled.

> Enabled, the server will send a CF List with every other join.
> Disabled, the server will not send a CF List. The channel mask is still transmitted via ADR command.

This feature ONLY applies to US915 regions. Until very recently Helium mistakenly had reversed the CHMask bytes in the Join response.  See - https://github.com/helium/router/issues/535.  It is likely that the supposed implementation flaw of U.S. end-device software was actually caused by the reversed ChMask bytes.

**Comment by mikev** [comment]
Lets also consider removing the CF List enable (U.S. only) feature completely.  My suspicion is this work-around was needed because the chmask was reversed, therefore when end-devices processed this, they started transmitting on the wrong channels.

**Comment by jdgemm** [comment]
> Lets also consider removing the CF List enable (U.S. only) feature completely. My suspicion is this work-around was needed because the chmask was reversed, therefore when end-devices processed this, they started transmitting on the wrong channels.

@mikev let's discuss this during sync call, thanks

**Comment by jdgemm** [comment]
Based on conversation, for future release we will make following changes:
- only send cflist for supported devices (1.1)
- remove alternating aspect of sending cflists
- change default from disabled to enabled

**Comment by Oliv4945** [comment]
Hi,

I just want to highlight that LoRaWAN 1.0.3+ devices are also compatible with a US CFList
