### ISSUE TITLE
Accommodate change to rx_delay from Console without device re-joining

### ISSUE THREAD

**Issue by dpezely** [helium/router#565]
Ticket for tracking development, testing/staging and deployment for Part 3 of `rx_delay`.

- Part 1 was [issue 531](https://github.com/helium/router/issues/531) and [PR#548](https://github.com/helium/router/pull/548) which has already been merged into `master`
- Part 2 was associated with same ticket and [PR#557](https://github.com/helium/router/pull/557)
- Part 3 (this one) -- [Accommodate change to rx_delay from Console without device re-joining](https://github.com/helium/router/pull/563)

EDIT: corrected link to first PR.

**Comment by dpezely** [comment]
Apparently, this feature is not completely correct.  See issue #571

**Comment by macpie** [comment]
We will continue work with https://github.com/helium/router/issues/571
