### ISSUE TITLE
OSS Console - Router wallet not returned, impossible to burn DCs

### ISSUE THREAD

**Issue by disk91** [helium/router#592]
Since update to version 2022.01.27 It not anymore possible to burn DCs for me
The api does not returns the router wallet ID and the the transaction can't be generated. (memo is correctly generated)
https://console.helium-iot.eu/api/data_credits/router_address return code 200
but body is:
```
{"address":""}
```

**Comment by jdgemm** [comment]
hi, team is continuing to investigate..

**Comment by disk91** [comment]
> Try kicking router container while console container is up.

It has no effect

**Comment by disk91** [comment]
I also update to the last release. No effect

**Comment by jdgemm** [comment]
The team is working on a patch to address this issue. Thanks for raising.

**Comment by slavendam** [comment]
@disk91 Do you have problem that it:
1. never returns address 
or
2. sometimes returns (it can join and send some uplink), and later it does not return?

**Comment by disk91** [comment]
Never returns ... at least all the time I have tested
You can do test on console.helium-iot.eu if you want ... it's open.
