### ISSUE TITLE
AWS IoT integration not working after console v2.2.2 release

### ISSUE THREAD

**Issue by Net-Metrics** [helium/router#613]
1. Are you using Helium hosted Console or running your own open source Console? Helium hosted

2. If you are on Helium hosted Console, which url are you currently on? 

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753). Org name - Net Metrics, Device ID - 50fc99bd-3b15-4e28-a753-519498725ce9

Please describe your issue:

All of my AWS IoT integrations stopped working at 9:00 p.m. last night when the console was down for maintenance, now that v2.2.2 has been released, these no longer work

Integration with Ubidots still running OK. AWS integration throws an error 4mins, 9mins & 14mins after uplink
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/80821734/153611344-3143b97b-44b0-4ecf-b895-43d1c2144b97.png">

<img width="883" alt="image" src="https://user-images.githubusercontent.com/80821734/153612151-609b320c-a05f-476a-b768-a3a78bd2d30c.png">

I have similar issue on all AWS integrations

<img width="496" alt="image" src="https://user-images.githubusercontent.com/80821734/153612368-c695d5c1-3861-4e26-807c-1b1f9d2436b0.png">

No indication of what the error is when viewing the integration itself. I tried re-entering the 'Secret key' to re-authorise connection, but this did not make any difference

I am connecting to AWS eu-west-1

Other users on Discord with same problem

**Comment by jens-meiss** [comment]
same here :-/

**Comment by macpie** [comment]
Issue is being actively looked at.

**Comment by macpie** [comment]
Problem identified, library for AWS was not updated with latest crypto Erlang OPT 24 module. It is being worked on now and we will be releasing as soon as this is fixed.

**Comment by jdgemm** [comment]
> I don't know if they are related but I have the same issue with azure.

Team's also investigating, but yes likely related...

**Comment by macpie** [comment]
> I don't know if they are related but I have the same issue with azure.

Please see https://github.com/helium/router/issues/619#issuecomment-1039745910
