### ISSUE TITLE
HIP46: Roaming 

### ISSUE THREAD

**Issue by mikev** [helium/router#615]
Implement HIP46 with the purpose to improve roaming scaling.
https://github.com/helium/HIP/blob/main/0046-lorawan-netid-routing.md

Tasks:
- [x] Explore options for new Chain Var with structure in blockchain-core Erlang library
      + Involved learning curve for members of router staff
- [x] Code for new chain var (suitable for testing, even if HIP has yet to pass)
- [x] Ancillary functionality for chain vars; e.g., update `add_block` event
- [x] Tests passing
- [x] https://github.com/helium/erlang-lorawan/issues/10
- [x] New chain var functionality merged into blockchain-core
    + https://github.com/helium/blockchain-core/pull/1285
- [ ] Utilize new chain var in gateway-rs
- [ ] Utilize new chain var in router
- [ ] Create new XOR Filter worker. It should be able to add: `app_eui/dev_eui,  app_eui (only), app_eui / dev_eui (range) `
- [ ] Update `gateway_rs` to handle new xor filter system

**Comment by pvolodin** [comment]
Does this mean it's too early to test Helium -> Senet roaming? One of my customers in US is pretty interested in this feature and asked me for some advices and assistance, but it looks like if we have to postpone this task.

**Comment by PharkMillups** [comment]
Not too early. Email me - ***@***.*** - and I can give you the full
details.

**Comment by pvolodin** [comment]
@PharkMillups 
> Not too early. Email me - ***@***.*** - and I can give you the full details.
> […](#)

I assume the email indicated on your Github profile is correct?

**Comment by mikev** [comment]
Design Notes - https://docs.google.com/document/d/1zgIuGdWpOpNFit1MtJ0aR7V4Cph4F09jo--RQYW99-Y/edit?usp=sharing

**Comment by mfalkvidd** [comment]
@mikev did you mean for those notes to be public? I'm getting a `You need access` message when clicking the link.

**Comment by dpezely** [comment]
[PR 1412](https://github.com/helium/blockchain-core/pull/1412) has been merged into `blockchain-core`, so state channels may make use of the new chain var once it gets officially published.
