### ISSUE TITLE
Enhancement - Create a downlink when receiving RxTimingSetupAnswer

### ISSUE THREAD

**Issue by Oliv4945** [helium/router#618]
When a device receives `RxTimingSetupReq` it must keep adding `RxTimingSetupAns` until it receives a downlink from the network server.

![image](https://user-images.githubusercontent.com/6248122/153841928-a7beb7b1-f221-4964-a90c-d91703ab9740.png)

Currently the router does not initiate any downlink upon reception of the `RxTimingSetupAns`, which is compliant to the LoRaWAN specification, but can be an issue especially in DR0 US915 where the payload is limited to 11 bytes: having 1 byte taken by the  `RxTimingSetupAns` is 10% of the available payload.

![image](https://user-images.githubusercontent.com/6248122/153852144-89f3bced-40f8-4ea1-95d5-7a9bf986c92d.png)

Maybe queuing a downlink after `RxTimingSetupAns` or after a few of them would help

**Comment by dpezely** [comment]
At first, this looked like a quick turn-around enhancement but requires more effort.
