### ISSUE TITLE
[FR] Eliminate the need of IP port forwarding

### ISSUE THREAD

**Issue by mrx23dot** [helium/router#644]
This would make installation lot easier for end gateway user. (plug and play)
It wouldn't even work with GSM networks (NATed IPs).

Why is it needed? 
Gateway receives a packet, forwards it to server , checks for answers.
Server doesn't have to initiate.

Even a smart lamp bulb can solve this, you can control it over a .com domain outside your house without port forwarding.

Even the block chain p2p can work behind router, see uTorrent. (uses multiple technics)

**Comment by mrx23dot** [comment]
For the full hotspot you could use UPnP to try automatic port forwarding over router.
If it fails user can still doe it manually.

**Comment by macpie** [comment]
> For the full hotspot you could use UPnP to try automatic port forwarding over router. If it fails user can still doe it manually. There is a linux lib for it.

This is already the case, see [here](https://github.com/helium/erlang-libp2p/tree/master/src/nat).
