### ISSUE TITLE
Fport missing in downlinks

### ISSUE THREAD

**Issue by mrx23dot** [helium/router#645]
I queued a downlink with port 1:
![2022-03-06_143430_Ll](https://user-images.githubusercontent.com/4163396/156927773-540253d7-7d91-484f-a092-89f4ecec21b9.jpg)

It went down:
![2022-03-06_143339_Yx](https://user-images.githubusercontent.com/4163396/156927730-c9430f4e-15dd-4ba8-ad22-4b8ad178942d.jpg)

```
category": "downlink",
"id": "112nEViXNuPJTMkhBjoJoDusBH1zWV9SAPZTASRy6WquKSkzdYiZ",
"port": 1
"payload_size": 12,
"payload": "YFwAAEgAAgDTqSH2",
"payload_hex ": 60 5c 00 00 48 00 02 00 d3 a9 21 f6
```

But it doesn't have a port:
![2022-03-06_143559_X0](https://user-images.githubusercontent.com/4163396/156927830-ef54324e-90e6-4f69-a458-c79bcb2adfca.jpg)

**Comment by pvolodin** [comment]
FPort missing in downlinks **if application payload length is 0**.

**Comment by mikev** [comment]
The FRMPayload is empty, therefore per the spec, "A frame with a valid FHDR, no FOpts (FOptsLen=0), no FPort and no FRMPayload is a valid frame."

**Comment by mrx23dot** [comment]
Thank you, we might want to visually indicate that in the manual downlink debug window.
(grey out port without user payload)

**Comment by pvolodin** [comment]
@mikev 
> "A frame with a valid FHDR, no FOpts (FOptsLen=0), no FPort and no FRMPayload is a valid frame."

But this doesn't mean a frame with non-empty FPort and no FRMPayload is invalid. 

![645_1](https://user-images.githubusercontent.com/1311823/157001421-63673fae-e974-43f1-8d67-4f9f073783ef.png)

So it's a bug, @mrx23dot I believe you should reopen this.

**Comment by mikev** [comment]
However the packet as described above is valid.  See the decode for confirmation:
https://lorawan-packet-decoder-0ta6puiniaut.runkit.sh/?data=YFwAAEgAAgDTqSH2&nwkskey=&appskey=

**Comment by pvolodin** [comment]
> However the packet as described above is valid.

Surely it is valid. It just differs from the packet sent from application layer. And that's the issue.

**Comment by pvolodin** [comment]
This is how correct packet should be looking like (though MIC is incorrect as I dont know the keys):
https://lorawan-packet-decoder-0ta6puiniaut.runkit.sh/?data=605C00004800020001D3A921F6&nwkskey=&appskey=

**Comment by mrx23dot** [comment]
Just tested uplink accepts packet with port and without user-payload,
so why can we do the same in downlink?

**Comment by mikev** [comment]
> Just tested uplink accepts packet with port and without user-payload,
> so why can't we generate the same in downlink?

The payload is empty and the spec allows either fport==1 or no fport.  No fport is more efficient from a library and transmit perspective, because you save one byte.  Is this a feature request?  Why do you want to generate such a Downlink packet?

**Comment by mrx23dot** [comment]
I want to store information in Port, without additional user payload.

- Port 0 is reserved for MAC codes, but 
- Port 1 could say TURN_ON
- Port 2 could say TURN_OFF
- ..
- till Port ~244 which is reserved for testing again.

Based on lorawan standards this is a valid usecase.

**Comment by pvolodin** [comment]
> The payload is empty and the spec allows either fport==1 or no fport.

Nothing in the spec allows the server to modify application-specific data. And FPort values 1..223 are application-specific.

> * till Port ~244 which is reserved for testing again.

224, to be exact

**Comment by Oliv4945** [comment]
Hi @mikev I also agree that the NS should not remove the port if the payload size is 0
