### ISSUE TITLE
Queue Downlinks Before Join

### ISSUE THREAD

**Issue by kent-williams** [helium/router#651]
A common strategy for device deployments is to queue downlinks prior to customers/users receiving the device and it joining for the first time. This is possible on other LNS, but not yet with Console/Router. This places an extra burden on the device manager to create logic for queuing downlinks after a join. Is this something we could allow without much effort?

**Comment by macpie** [comment]
@kent-williams The problem here is until we get a join we do not know the region of the device so we cannot properly calculate `Data Rate Down`. We would need to provide the region to downlink then and change UI, it that something you feel we should do?

**Comment by macpie** [comment]
@kent-williams I was able to queue a downlink before a join could you confirm it is working on your end?

**Comment by kent-williams** [comment]
@macpie Are you able to queue before the very first join? I believe @michaeldjeffrey clarified this in chat.

**Comment by macpie** [comment]
We have decided to add an option to include region when sending a downlink. Router and Console will need to support this.

**Comment by macpie** [comment]
Fixed in https://github.com/helium/router/pull/732
