### ISSUE TITLE
LoRaWAN Library

### ISSUE THREAD

**Issue by mikev** [helium/router#660]
To make our project simpler, higher quality and easier to maintain we are working on a separate LoRaWAN library project which will integrate with Router.  This parent ticket will track the high level library plan, roadmap and progress.

The library will be accessed by Miner, Router, Blockchain-Core and gateway-rs.  We expect substantial portions of Router to be removed and replaced by LoRaWAN API calls.

The library is in a separate repo - https://github.com/helium/erlang-lorawan

Encode/Decode for 1.0 complete
ADR Engine complete
Regional in-progress

Plan:

- [ ] Review and merge lora_subnet into master.
- [x] https://github.com/helium/router/pull/710
- [ ] https://github.com/helium/router/issues/664
- [ ] Review defensive code strategy (library will be brittle or defensive?)
- [ ] Review & Merge lorawan library
- [ ] Integrate lora_plan with on-chain variable data.
- [ ] Parameterize CT tests, e.g. <<rssi> == 30

Child Tickets:
https://github.com/helium/router/issues/664

**Comment by mikev** [comment]
Regional library code is in-progress.  Regional code handles channel frequency plan logic, which implement the dozen channel plans defined by the LoRaWAN Regional spec, e.g. EU868, AS923-1 and US915.

**Comment by macpie** [comment]
Regional code PR: https://github.com/helium/router/pull/710
