### ISSUE TITLE
Prometheus Grafana Templates

### ISSUE THREAD

**Issue by disk91** [helium/router#679]
The docker-compose template does not expose the port 3000 for getting access to metrics for prometheus in the template where network is not host.

I recommend to expose the port 3100 instead of 3000 because grafana uses port 3000 so this is a bit confusing as it conflict or prometheus load the grafana metrics instead of the router metrics...

Prometheus template file is => 3000 = grafana port
scrape_configs:
  - job_name: router
    static_configs:
      - targets: ['127.0.0.1:3000']

**Comment by macpie** [comment]
The option is there we just need to expose it so default port can be changed
