### ISSUE TITLE
router organization info all does not display the org UUID correctly

### ISSUE THREAD

**Issue by disk91** [helium/router#682]
When you use command

```
docker exec helium_router router organization info all
|fc40xxx-xxxxx-xxxxx-xxxxx-aaf31b|       xxxxxxx        |undefin| 0  | undefined  |undefined |
```
you get an oragnization number but when you do:

```
docker exec helium_router router organization info fc40xxx-xxxxx-xxxxx-xxxxx-aaf31b
Organization not found.
ok
```

So there is a problem somewhere

**Comment by macpie** [comment]
@disk91 Is this still an issue? I was unable to reproduce.

**Comment by disk91** [comment]
Yes : the reason is info all does not display the organization id full but as a substring
ex : 
```
what is returned
|ad00a606-xxxx-xxxx-b312-adf433|          Helium IoT      
the real id
ad00a606-xxxx-xxxx-b312-adf433xxxxfa
```

**Comment by michaeldjeffrey** [comment]
The table printer will do its best to fit the results in the space you give it. 
Does this continue to happen if you make your terminal wider?
