### ISSUE TITLE
Downlink enqueued after a TX and before RXs windows opening are not sent immediately 

### ISSUE THREAD

**Issue by Achichig** [helium/router#684]
**Describe the bug**
When a downlink is enqueued after sending an uplink but before opening the RX1 and RX2 windows, the downlink is not sent immediately to the gateway, regardless of the RX1 delay, but will wait for a second uplink to send the downlink on the second RX1/RX2 windows.

![image](https://user-images.githubusercontent.com/101577545/161972668-1591e7dc-ba75-47cb-9616-00058899782a.png)

**To Reproduce**
- Configure RX1 delay with any value
- Send an uplink
- Quickly enqueue a downlink

**Expected behavior**
I expect the downlink to be sent to the RX1/RX2 windows relative to the first uplink.

![image](https://user-images.githubusercontent.com/101577545/161973178-6ab71af6-2ab0-4a7e-9826-4cc0af30e2f6.png)

**Device Info (please complete the following information):**
 - Environment (Production, Staging): production
 - Console Device ID: 4be56505-ca63-4440-8de7-114e2b22bb10
 - Device dev eui / app eui: ACACACACACACAC12/ACACACACACACAC12
 - How often is device sending data: Regularly
 - Region: EU868
 - Hotspots (names) used to transfer data: fast-hickory-raven/Real Smoke Nightingale

*NOTE: do not post your device `app_key`*

**Comment by macpie** [comment]
Yes this is right. The Router at that point as already made the decision to send (or not) the downlink.

The rx window (or rx delay) is then applied at the hotspot level.

**For a downlink to be sent it needs to be queued before an uplink**.

**Comment by Oliv4945** [comment]
> Yes this is right. The Router at that point as already made the decision to send (or not) the downlink.
> 
> The rx window (or rx delay) is then applied at the hotspot level.
> 
> **For a downlink to be sent it needs to be queued before an uplink**.

Hi, this is not how LoRaWAN network server usually work, and while an application should be able to cope with a downlink sent on the next uplink it usually allow optimizations that save power and network capacity.  
Would you mind to check if that changing this behavior is a complicated thing on your side?

Thanks

**Comment by macpie** [comment]
Unfortunately it would be a major change as most of this lives on the Hotspot

**Comment by jamesl-dm** [comment]
I consider this a major bug as well. When the end-node is requesting something from it's application server (for instance, the current time) it now has no chance of receiving a reply, and will always have to send the request twice, and process the reply twice. Even if the RxDelay has been set to 15 seconds. I don't know of any other network server that has this design. Usually the network server will make the downlink decision later, at some fraction of the RxDelay.

**Comment by Oliv4945** [comment]
> Unfortunately it would be a major change as most of this lives on the Hotspot

Even with the upcoming gateway-rs switch? Can't a hotspot open a gRPC bidirectionnal streaming that the router can use to push the downlink to the hotspot, or close it after `RxDelay` if it has not received any downlink from the AS?
