### ISSUE TITLE
Network Time Request reply

### ISSUE THREAD

**Issue by EwanBez** [helium/router#689]
Don't see a way to allow for network time request reply to be sent on the next down link.
Expected to find it in profiles maybe - similar to ADR or RX slot time delay? 
![HeliumDeviceTimeReq](https://user-images.githubusercontent.com/88307657/162621297-79e1dd00-d8bc-40ec-8f63-0804ce4865dc.PNG)

**Comment by macpie** [comment]
I do not think we support the `network time request` at this moment.

**Comment by Oliv4945** [comment]
Hi, I also need this for some projects.

This MAC command has been added in LoRaWAN spec v1.0.3, what is your current plan regarding 1.0.4 @macpie? I saw #445 but it seems to be stalled

**Comment by Sensative-Lars-Mats** [comment]
Solving https://github.com/helium/router/issues/637 does not solve this issue in itself. The need is really to support 1.0.3 or 1.0.4 LoRaWan.
