### ISSUE TITLE
XOR Filters Fees

### ISSUE THREAD

**Issue by macpie** [helium/router#692]
XOR Filter fees can grow very large if a Router/Console is adding a lot of devices.

1. We should propose a HIP: Fees should not be calculated on the full size of filter but rather on the difference with the previous update.
2. We can then update XOR filter code to balance filter again

**Comment by macpie** [comment]
PR https://github.com/helium/blockchain-core/pull/1303

**Comment by jdgemm** [comment]
HIP 59:

https://github.com/helium/HIP/blob/main/0059-reduce-xor-filter-fees.md
