### ISSUE TITLE
Getting error when applying new filter

### ISSUE THREAD

**Issue by CanEmreUnal** [helium/router#711]
Router is getting error when applying xor filter to blockchain.

Devices are stuck on 'pending' state.

`[2022-04-25 14:48:52.241] <0.1645.0> [warning] [blockchain_txn:validate:{327,21}] invalid txn blockchain_txn_routing_v1 : {error,{bad_nonce,{routing,11,11}}} / type=routing oui=26 owner="112tbU2H7bwDrRPHK8vGpC1VnVHBg914WKenEbhjiyZZHg8qEJgr" update={update_xor,`

Router and Console carrying the latest tag on quay.

**Comment by michaeldjeffrey** [comment]
If you've done transactions elsewhere around the same time router was attempting a transaction, they can conflict with each other. A solution last time this happened was to turn off the xor filter for a few blocks to let the nonce stabilize, then let it try again.

https://discord.com/channels/404106811252408320/730245319882965093/963204249267896331

**Comment by CanEmreUnal** [comment]
Allright I'll try that one.. 

If so, Is there a way to trace uncommitted/not cleared transactions for xor filter for specific peer ?

**Comment by michaeldjeffrey** [comment]
While it's being considered, you can run the command 
```
router txn queue```
If it's not accepted, it will be dropped and doesn't go anywhere.

**Comment by CanEmreUnal** [comment]
Gotcha thanks!
