### ISSUE TITLE
AWS Integration Issue

### ISSUE THREAD

**Issue by charlesfayal** [helium/router#720]
1. Are you using Helium hosted Console or running your own open source Console?
Dedicated Console (But it also occurred on production console)

2. If you are on Helium hosted Console, which url are you currently on? 
console-vip
3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
4684846d-0d3f-44e5-8adc-bb68b6c2a426

Please describe your issue:
For specific devices, we get integration issues. It seems to be correlated with the frequency of packets (more packets = higher frequency of integration issue).
The integration as a whole isn't failing just specific devices. They also seem to self-heal after some amount of time (up to a day or more).
This can cause devices to seemingly go down for extended periods.

Debug:
`{
  "category": "uplink",
  "description": "Error: failed_to_publish",
  "device_id": "240fba2c-27c8-4d39-b04e-16c5ecb43fb2",
  "device_name": "TEST (V2-2)",
  "id": "f3275e7e-53b0-498e-8de3-6b8538ee81c6",
  "inserted_at": "2022-05-04T16:39:46",
  "organization_id": "4684846d-0d3f-44e5-8adc-bb68b6c2a426",
  "reported_at": "1651682386666",
  "reported_at_naive": "2022-05-04T16:39:46",
  "router_uuid": "1fababdd-3e8c-4ee3-95dc-652a99d2a58f",
  "sub_category": "uplink_integration_req",
  "updated_at": "2022-05-04T16:39:46"
}`
`{
  "category": "uplink",
  "description": "Error: failed_to_publish",
  "device_id": "240fba2c-27c8-4d39-b04e-16c5ecb43fb2",
  "device_name": "TEST (V2-2)",
  "id": "9bfc3045-39b5-4423-ac21-ad5e66505897",
  "inserted_at": "2022-05-04T16:39:46",
  "organization_id": "4684846d-0d3f-44e5-8adc-bb68b6c2a426",
  "reported_at": "1651682386666",
  "reported_at_naive": "2022-05-04T16:39:46",
  "router_uuid": "1fababdd-3e8c-4ee3-95dc-652a99d2a58f",
  "sub_category": "uplink_integration_res",
  "updated_at": "2022-05-04T16:39:46"
}`

**Comment by hwahby** [comment]
Hi, @charlesfayal. Is this issue still occurring? If so, are there new device Ids? It would help troubleshoot on our side.

**Comment by charlesfayal** [comment]
Honestly, it might just be best for somebody to connect to our alerts for NOWi Sensors. There's at least a few a day now that I'm connected to the alerts.
Generally, it's not a huge deal, but on multiple occasions, we've had important test nodes go down with clients watching.

**Comment by hwahby** [comment]
@charlesfayal I'm happy to be added to alerts.

**Comment by charlesfayal** [comment]
@hwahby okay, what's your email? I'll invite you to our org.

**Comment by hwahby** [comment]
Thank you, @charlesfayal. My email is hady@nova-labs.com.

**Comment by macpie** [comment]
> Thank you, @charlesfayal. My email is hady AT nova-labs DOT com

Edited for privacy.

**Comment by charlesfayal** [comment]
Sent

On Fri, May 27, 2022 at 11:37 AM macpie ***@***.***> wrote:

> *Message sent from a system outside of UConn.*
>
> Thank you, @charlesfayal
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcharlesfayal&data=05%7C01%7C%7C38b70b8789cf4cbe8d3b08da4010012d%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637892734730512007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O5WJvz36kKLc4q5D8JNq4QVr1QX%2FCCoj8dBUat0AOrk%3D&reserved=0>.
> My email is hady AT nova-labs DOT com
>
> Edited for privacy.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhelium%2Frouter%2Fissues%2F720%23issuecomment-1139930155&data=05%7C01%7C%7C38b70b8789cf4cbe8d3b08da4010012d%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637892734730512007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DnVfWuRdg9TmBsGOuBrOW60ybe8vIfpejIQywTioL14%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD3IIBFRKBUGGYLGKKN7CUTVMEI75ANCNFSM5VCR64VA&data=05%7C01%7C%7C38b70b8789cf4cbe8d3b08da4010012d%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637892734730512007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0L1B7stO61bRJgBUcpuL1YnRgaYc3mibqkFlZhWHxps%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
University of Connecticut
Biomedical Engineering,  2015
Electrical Engineering,  2016
Cell: 860-941-5547
