### ISSUE TITLE
Add Support for Regions IN865 and KR920

### ISSUE THREAD

**Issue by mikev** [helium/router#740]
The Helium Network currently lacks support for the IN865 and KR920 frequency region plans.  With this ticket we'll update and QA these plans so that Hotspot owners in India, Pakistan and South Korea can use the Helium network.

Fully supporting a new Region frequency plan requires coordination and support from the Router, Gateway-RS, H3, firmware and various other projects.  Finally it also requires some level of software and hardware QA testing to validate that real IN868 end-devices can physically connect and Join to an IN868 Hotspot.

One significant difference with IN865 is that frequencies must be detected to 4 significant decimals, e.g. 865.0625.  Therefore frequency rounding of float values needs to be more carefully coded.

**Comment by mikev** [comment]
LoRaWAN library update
https://github.com/helium/erlang-lorawan/pull/6/files

**Comment by mikev** [comment]
Library changes merged to master
https://github.com/helium/router/pull/748

**Comment by jdgemm** [comment]
duplicated, by #771, #762
