### ISSUE TITLE
Downlink issues

### ISSUE THREAD

**Issue by r4wk** [helium/router#754]
1. Are you using Helium hosted Console or running your own open source Console? Helium Hosted

2. If you are on Helium hosted Console, which url are you currently on? N/A

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753). r4wknet, b49366bf-b8fe-4c03-900f-444ef87b4c78, ab0f9eb5-dd18-47f0-b058-a610cccd29d5

Please describe your issue:
Downlinks are not being received by my devices. Seems they stopped working right at the time of the recent console update. Downlinks are being que'd in the console but they never make it to my devices. Unfortunately there's no way for my to prove this is something on the console's side other than the fact that this has been working for months. I've noticed uplinks have a spreading of SF7 and downlinks have a spreading of SF8. In the past, when downlinks were working, both would be SF7. I've also noticed since the console update the channel on downlinks is always 0. Where before it appeared to be a random channel. Below is a paste bin of some JSON showing the difference between a working downlink (pre update), and and not working one. The pastebin is only an example, if you look at my devices you should see hundred's of examples of this (if not 1000+). The two sensors I'm using to debug are WisBlock's running mapper firmware. Please let me know if you need anything else.

Edit: Also tried adding one of the devices to a second console account with seemingly no success. Any insight would be welcome!

https://pastebin.com/tmXWfmsz

**Comment by macpie** [comment]
Was this fixed with `2022.05.12.8`? We reverted our LoraWan implementation due to some downlink issues

**Comment by r4wk** [comment]
> issues

Yup! happy to be getting downlinks again. thank you. 
![20220523_182054](https://user-images.githubusercontent.com/5049300/169912430-39383de4-6ef1-4992-9567-9649dfd1e900.jpg)

**Comment by macpie** [comment]
Awesome! Glad to see a happy device!
