### ISSUE TITLE
Clarifying the Definition of DevAddr Slab

### ISSUE THREAD

**Issue by lytzV** [helium/router#767]
Logging the conversation around the formal definition of DevAddr slab

**Conclusion**
A slab is a range of device addresses that can be purchased by an OUI. A slab of size n, also sometimes abbreviated as _n slab_, holds n device addresses. For instance, the "1024 slab" shown in the picture below refers to a range of 1024 device addresses.
<img width="1024" alt="Screen Shot 2022-05-26 at 2 17 41 PM" src="https://user-images.githubusercontent.com/44751312/170581782-e041357b-5dfb-4dc2-9295-978cd88d86f8.png">

This is corroborated by the code linked below
- https://github.com/helium/blockchain-core/blob/0ec9d80d582d810ba2e7eda30921d9ad1eb6cf71/src/ledger/v1/blockchain_ledger_v1.erl#L3584
- https://github.com/helium/blockchain-core/blob/0ec9d80d582d810ba2e7eda30921d9ad1eb6cf71/src/ledger/v1/blockchain_ledger_v1.erl#L3610
- https://github.com/helium/blockchain-core/blob/0ec9d80d582d810ba2e7eda30921d9ad1eb6cf71/src/ledger/v1/blockchain_ledger_routing_v1.erl#L155
- https://github.com/helium/blockchain-core/blob/0ec9d80d582d810ba2e7eda30921d9ad1eb6cf71/src/ledger/v1/blockchain_ledger_routing_v1.erl#L159

Suggested Tasks:
- [ ] Write simple `eunit` test utility to exercise / confirm number of addresses available for various size "slabs"
  + Understand these *addresses* to be distinctly **different than** concurrent *devaddr* allocations
- [ ] Exercise 8 slab
- [ ] Exercise 16 slab
- [ ] Exercise 256 slab
- [ ] Exercise 1024 slab
- [ ] Reference those tests for customers at large; e.g., on `docs.helium.com` website

**Comment by macpie** [comment]
Doc here: https://github.com/helium/docs/pull/930
