### ISSUE TITLE
KR920 device not join accept on console

### ISSUE THREAD

**Issue by bryanuk72** [helium/router#772]
1. Are you using Helium hosted Console or running your own open source Console?
Helium hosted Console.
2. If you are on Helium hosted Console, which url are you currently on? 
console.helium.com
3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
Organization name: NXQUBE ,  Device ID:75980454-7694-4d4f-be6f-a13cef0d2947(Milesight AM-107Temp sensor), cdb067b6-3b72-4ca0-a106-4abb0a409bf6 (Winext AN-106 Lora Tester)
Please describe your issue:
I have registered 2 devices to the console, but not join accept. 
This device only supports the KR920 and is used in Korea.
Doesn't Helium Console support KR920 yet?

**Comment by mikev** [comment]
We do not support KR920.  Support is coming soon.
https://github.com/helium/router/issues/740
