### ISSUE TITLE
Helium_gateway is not sending data : state channel error Service

### ISSUE THREAD

**Issue by yaser7us** [helium/router#774]
Hotspot is not able to send data and I keep getting this error message on the helium_gateway:

state channel error Service(Rpc(Status { code: Unknown, message: "error reading a body from connection: stream error received: received frame when stream half-closed", source: Some(hyper::Error(Body, Error { kind: Reset(StreamId(13), STREAM_CLOSED, Remote) })) })), oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router

**Comment by macpie** [comment]
This most likely means that the Router refused that specific packet and then close the connection. I do no thing this is anything to worry about. I would note that maybe we can do a better at displaying the error in `gateway_rs`
