### ISSUE TITLE
Evolution request - device auto decomissining 

### ISSUE THREAD

**Issue by disk91** [helium/router#776]
On a router the devaddr resources are costly (about $1 per device, corresponding to 100.000DCs) considering with can have a overasignement of 100 devices per DevAddr.

The problem is that many devices are not removed from the console as it is a non cost for users. This pollute the XOR filters with non active devices. and force to increase the DevAddr pool for a reduced number of active devices. The economical impact is large.

The evolution request is to automatically decommission (remove the device from the XOR filter with a button to re-insert it later) after a certain time of inactivity (no join request, no uplink), this duration would be in a setting the router owner can select. I think the right unit is in days and the idea is to have a default inactivity period of 60 days.

**Comment by macpie** [comment]
Until [HIP 59](https://github.com/helium/HIP/blob/main/0059-reduce-xor-filter-fees.md) this was too costly to do. We have now plans to rewrite the XOR Filter handler so that it can support removal. 

I will link this ticket as soon as I have more details.
