### ISSUE TITLE
Support AS923-1 in Pakistan

### ISSUE THREAD

**Issue by mikev** [helium/router#804]
Currently the Helium network uses IN865 in Pakistan.  Helium has a customer contact in Pakistan and the customer has determined that IN865 is not legal within Pakistan.  This is primarily because the 800 Mhz band is not intended for IoT in Pakistan, but also the 800 Mhz band in Pakistan is limited to 10 mW but IN865 uses 1000 mW.  The customer has shared regulatory documents which confirm these facts.

Further regulatory details from the customer:
https://github.com/helium/miner/issues/1741

After a discussion with other Helium engineers and the Helium Foundation we've reached consensus that AS923-1 is the correct plan.  AS923-1 is also listed in the LoRa Regional Spec.

Note - the same issue exists for Jordon which is also assigned IN865.  It is advisable to switch Jordon to AS923-3.

Currently Pakistan has ~100 Hotspots and Jordon has ~10 Hotspots.

**Comment by mikev** [comment]
AS923-1 deployed

**Comment by iwebconsultants** [comment]
Hi Team, 

Can I please request to review, as the frequency page is still showing Pakistan in IN865:

https://docs.helium.com/lorawan-on-helium/frequency-plans/

Are you able to assist please ?

Regards,

Azam

**Comment by waveform06** [comment]
https://docs.helium.com/lorawan-on-helium/frequency-plans/ has been updated
