### ISSUE TITLE
Missing Uplinks

### ISSUE THREAD

**Issue by RTK221B** [helium/router#817]
Skylab has been noticing immense packet loss. They have a potential 5000 device deployment stuck due to this. They’re seeing 30-40% loss in uplinks. There's a probability that there's an overflow of data not getting forwarded to the console. Sensors that were working prior to the LHS update are no longer working. They have observed that the data was reaching the hotspot but is being dropped on the way to the LNS. They're also not seeing join attempts or accepts. The current gateways they are using are LongAP and Kerlink. Devices have also been rebooted/power cycled.

**Comment by jdgemm** [comment]
Let's see if the new miner update has had a positive impact on their situation like we've seen with other users: https://engineering.helium.com/2022/07/14/miner-hotspot-release.html

**Comment by Net-Metrics** [comment]
I'm still seeing this on some devices, others behave as expected. Don't know if it could be related but thought I'd post just in case it points towards something.

My devices with missing uplinks are the same devices that have the LinkADRReq/LinkADRAns Looping issue 

https://github.com/helium/router/issues/791

On a device that behaves as expected I see the following
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/80821734/184532158-8431679d-323b-4b33-8490-8ad1a8f680e2.png">

This device successfully transmits almost all of it's uplinks, you can see 1 missed uplink at the start of this, every other one was received
<img width="1825" alt="image" src="https://user-images.githubusercontent.com/80821734/184532335-d3ab7d89-0027-4fe5-8e04-e4616b4aff78.png">
 

Contrast this with the device that has issues
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/80821734/184532203-a95dff88-985b-4041-9a73-e765927b5b21.png">

Received uplinks, this sensor missed 15 uplinks over the same period
<img width="1825" alt="image" src="https://user-images.githubusercontent.com/80821734/184532373-1d5cd10a-04ef-4f54-8d81-60ccbe4fe960.png">
