### ISSUE TITLE
Packet forwarding stops randomly in gateway-rs until process is restarted

### ISSUE THREAD

**Issue by vkynchev** [helium/router#830]
**Describe the bug**
After the hotspot upgrade to disable chain sync and mux enable I’ve started to experience packet forwarding issues. After the device/container is started everything works perfectly fine, but after a random period of time (couple hours) packet forward to console stops working. Packets are not forwarded to the router and get discarded on the hotspot. This is fixed by restarting the container. I’ve tried to get help in #gateway-development channel (@madninja and jerm were assisting me there) - https://discord.com/channels/404106811252408320/784462269072277576/1000734780305977359

**To Reproduce**
Can't reproduce reliably. Happens at random intervals (6h+ after starting the container), but at least once per day.

**Expected behavior**
Packets should be forwarded and accepted by the router/console without any issues.

**Device Info (please complete the following information):**
 - Environment - Production (dedicated Nova console)
 - Console Device IDs - Device 1 ` 1e4000d9-083c-4bc8-a16d-545a8b9a8ae5` / Device 2 `e6fb7c05-d131-43c6-95cd-4a2b3625f2e6`
 - Device dev eui / app eui - Device 1 `5002913621981880` / Device 2 `5002913621983B4C` / App EUI `6081F9C80023ADC6`
 - How often is device sending data - one packet per minute (usually gateway receives around one per 2-3 minutes, coverage is not ideal)
 - Region - Bulgaria, Europe
 - Hotspots (names) used to transfer data - Restless Plastic Tadpole

**Additional context**
Log 1: https://pastebin.com/dADHcHt7 / `p@ssw0rd` / packets stopped being forwarded around 09:53-09:54
Log 2: https://pastebin.com/qdrj8NnC / `p@ssw0rd` / packets stopped being forwarded around 04:29

Full log from today (packet forwarding stops around 04:29): 
[console.log](https://github.com/helium/router/files/9182534/console.log)
[crash.log](https://github.com/helium/router/files/9182536/crash.log)
[error.log](https://github.com/helium/router/files/9182539/error.log)

**Screenshots**
_none_

**Comment by jerm** [comment]
I don't think that was me ;)

**Comment by vkynchev** [comment]
@jerm oh, sorry, the discord handles got copied over when I created the issue… I’ll untag you :)

**Comment by lytzV** [comment]
A new hotspot firmware (2022.08.02.0) was released yesterday along with a fix to this issue. Once your hotspot firmware is updated, would you mind running your experiment again and verify the results? Thanx!

**Comment by vkynchev** [comment]
@lytzV Thanks for letting me know. I’ll monitor the hotspot for a few days and give you feedback.

**Comment by vkynchev** [comment]
@lytzV I can confirm everything works butter-smooth now!
