### ISSUE TITLE
AS923-1 deployed

### ISSUE THREAD

**Issue by iwebconsultants** [helium/router#859]
AS923-1 deployed

_Originally posted by @mikev in https://github.com/helium/router/issues/804#issuecomment-1216910400_

Hi Team,

Can I please request to review, as the frequency page is still showing Pakistan in IN865:

https://docs.helium.com/lorawan-on-helium/frequency-plans/

Are you able to assist please ?

Regards,

Azam

**Comment by mikev** [comment]
The docs were updated 15 days ago.  Please allow some time for the doc update to deploy to the web site.
https://github.com/helium/docs/commit/05e0cd08fb0061741e968b6237880ba1e4650f56
