### ISSUE TITLE
Device migration script from Router/Console to Chripstack

### ISSUE THREAD

**Issue by macpie** [helium/router#871]
- [ ] Find a way to compile Chirpstack's GRPC apis https://github.com/chirpstack/chirpstack/blob/master/api/proto/api/device.proto
- [ ] Use `router_cli_device_worker` to create a CLI to get all device from Console
- [ ]  ....

**Comment by Dangerousfish** [comment]
Hope this helps:

GET https://console.helium.com/api/v1/devices
https://docs.helium.com/api/console/#devices-list

Chirpstack:
POST http://<_ChirpStackHost_>:8080/api/devices
http://35.160.9.254:8090/#/DeviceService/DeviceService_Create

https://www.chirpstack.io/docs/chirpstack/api/grpc.html

**Comment by macpie** [comment]
> Hope this helps:
> 
> GET https://console.helium.com/api/v1/devices https://docs.helium.com/api/console/#devices-list
> 
> Chirpstack: POST http://<_ChirpStackHost_>:8080/api/devices http://<_ChirpstackHost_>:8090/#/DeviceService/DeviceService_Create
> 
> https://www.chirpstack.io/docs/chirpstack/api/grpc.html

Thank you any help is always welcomed!

**Comment by macpie** [comment]
Device GRPC def https://github.com/chirpstack/chirpstack/blob/master/api/proto/api/device.proto

**Comment by lytzV** [comment]
chrpstack migration in english

https://docs.google.com/document/d/1k99_yt41_gV3KVUD9EIYfX_qWdJxl3y6sn-U0jkwcwU/edit?usp=sharing

**Comment by macpie** [comment]
Was done by third party
