### ISSUE TITLE
disable device euis still shows data

### ISSUE THREAD

**Issue by ccall48** [helium/router#977]
**Describe the bug**
on disabling a device in fdn console the device euis do not appear to be removed from router route id all the time.

**To Reproduce**
disabled device in fdn console will show activity and in some cases interrupt join/accept if the device has been moved to an open lns. 

**Expected behavior**
confirmed removal of device euis from fdn route id on a disable toggle.

**Device Info (please complete the following information):**
 - Environment (fdn console -> openlns)
 - Console Device ID -> dragino LG92
 - Device dev eui / app eui (A84041F951822355 / A840413461822355)
 - How often is device sending data -> only when it triggers movement or on a reset to rejoin.
 - AU915
 - Hotspots (names) used to transfer data -> unsure the openlns gwmp doesnt give us the hotspot name, b58 or asserted coords.

*NOTE: do not post your device `app_key`*

**Additional context**
the workings seem to be intermittent and it does seem to interfere with moving the device to another LNS and route id.
sorry the screenshots are not perfect. the fdn console devices have been disabled for last week or more and were added to our LNS route id one joined after some time and the other was just sending join/accepts.

i have released both these device euis off our route and put them back onto the fdn console for time being.  

**Screenshots**
If applicable, add screenshots (from Console) to help explain your problem.
![Screenshot_20230708_122415_Chrome](https://github.com/helium/router/assets/34887996/aa03ade1-07c0-47be-943b-6649e8155968)
![Screenshot 2023-07-08 at 13 28 55](https://github.com/helium/router/assets/34887996/2ecbc75e-ef19-43f2-93e9-ea89a182a05e)

![Screenshot 2023-07-08 at 13 56 48](https://github.com/helium/router/assets/34887996/d6d8f57e-c725-4af2-946d-e3d75be59485)

**Comment by macpie** [comment]
Thank you I really appreciate the details, we will bellowing into this.

**Comment by michaeldjeffrey** [comment]
I believe this should be fixed by PR https://github.com/helium/router/pull/985.

Inactive devices were being incorrectly filtered out of the local cache of devices, so were not being considered for removal when we compared them to the list of devices from Console.
